% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name task_1
%  @associatedFile /MATLAB Drive/lab7/task_1.m
%  @mostRecentlyActioned true
%  @uniqueId 91D42ED8

task_1

%% @name task_123
%  @associatedFile /MATLAB Drive/lab10/task_123.m
%  @mostRecentlyActioned true
%  @uniqueId 6916F840

task_123

%% @name confusion_matrix
%  @associatedFile /MATLAB Drive/Skin-Cancer-Detection-System-using-Image-Processing/confusion_matrix.m
%  @mostRecentlyActioned true
%  @uniqueId 25FC57CB

confusion_matrix

%% @name task_123LPF
%  @associatedFile /MATLAB Drive/lab12/task_123LPF.m
%  @mostRecentlyActioned true
%  @uniqueId 3D547F64

task_123LPF

%% @name task123HPF
%  @associatedFile /MATLAB Drive/lab12/task123HPF.m
%  @mostRecentlyActioned true
%  @uniqueId 2B2EB164

task123HPF

