% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name task_8
%  @associatedFile /MATLAB Drive/lab5/task_8.m
%  @mostRecentlyActioned true
%  @uniqueId 468A0158

task_8

